
# application.properties support only strings as values,
# whereas application.yml supports multiple data types, including numbers, booleans, arrays, and objects.
# This makes YAML more flexible and suitable for applications with complex configuration requirements.


#Data source configuration
spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: uu.qoEW)w2a9147

  #Disable Thymeleaf template caching;
  #Before deploying the application in a production environment - set (truth);
  thymeleaf:
    cache: false

  #Hibernate configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true


  #For POST,PATCH...methods
  mvc:
    hiddenmethod:
      filter:
        enabled: true


